version: 1.0.{build}

os: Visual Studio 2015

shallow_clone: true

environment:
  deployment_password:
    secure: i2xNSnZMjUY1cb6okh+wAKuE1Mq5QTT/soEB5fDHbQQ/kECcB8B5c9GAkQLh9x7Ua4PKEib0zeYsLOKduBb4zQ==

init:
- node --version
- npm --version

before_build:
- npm install
- dotnet restore

build_script:
- node_modules\.bin\webpack --config webpack.config.prod.js
- dotnet build --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%

after_build:
- dotnet publish --configuration Release --output publish --no-build
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp="%APPVEYOR_BUILD_FOLDER%\publish" -dest:IisApp=subtitleevaluation,ComputerName=https://subtitleevaluation.scm.azurewebsites.net/msdeploy.axd,UserName=$SubtitleEvaluation,Password="%deployment_password%",AuthType=Basic -retryAttempts:2'

test: off

artifacts:
- path: publish
  name: Release
  type: WebDeployPackage

