export default {
  MERGEABLE: 'MERGEABLE',
  TOO_LONG_ROWS: 'TOO_LONG_ROWS',
  TOO_MANY_CHARACTERS: 'TOO_MANY_CHARACTERS',
  TOO_MANY_ROWS: 'TOO_MANY_ROWS',
  TOO_SHORT_DURATION: 'TOO_SHORT_DURATION',
  TOO_LONG_DURATION: 'TOO_LONG_DURATION',
  TOO_LITTLE_CPS: 'TOO_LITTLE_CPS',
  TOO_BIG_CPS: 'TOO_BIG_CPS',
  TOO_SHORT_PAUSE: 'TOO_SHORT_PAUSE',
}
