const errorTypes = {
  NO_PROBLEM: 'NO_PROBLEM',
  MERGEABLE: 'MERGEABLE',
  TOO_LONG_ROWS: 'TOO_LONG_ROWS',
  TOO_MANY_CHARACTERS: 'TOO_MANY_CHARACTERS',
  TOO_MANY_ROWS: 'TOO_MANY_ROWS',
  TOO_LONG_DURATION: 'TOO_LONG_DURATION',
}

export default errorTypes
